### ISSUE TITLE
Support berkshelf 4.0

### ISSUE THREAD

**Issue by koertkuipers** [bbaugher/chef-berksfile-env#5]
love this plugin, but with latest chefdk i run into this issue:
```
$ knife environment from file environments/dev.rb
ERROR: Gem::LoadError: Could not find 'berkshelf' (~> 3.0) - did find: [berkshelf-4.0.1]
```

**Comment by bbaugher** [comment]
Done by 9655fc35ca5f33c988dd21b104fd7ec45cd19c32

**Comment by bbaugher** [comment]
This was released as 1.3.0

**Comment by koertkuipers** [comment]
thanks! that was quick.

i still have an issue, but i believe this is related to knife and berkshelf requiring different versions of httpclient somehow. i will ask chefdk community to address this.

$ knife environment from file environments/dev.rb 
ERROR: Gem::ConflictError: Unable to activate berkshelf-4.0.1, because httpclient-2.7.0 conflicts with httpclient (~> 2.6.0)
